### ISSUE TITLE
owlAllValuesFrom2shClassOrDatatype references non-existent SPARQLFunction

### ISSUE THREAD

**Issue by simonstey** [sparna-git/owl2shacl#1]
All 3 shapes graphs reference a sh:SPARQLFunction that doesnt exist ([only in the original shapes graph ](https://github.com/sparna-git/owl2shacl/blob/main/owl2sh-original.ttl#L195))

1. https://github.com/sparna-git/owl2shacl/blob/main/owl2sh-closed.ttl#L841
2. https://github.com/sparna-git/owl2shacl/blob/main/owl2sh-open.ttl#L834
3. https://github.com/sparna-git/owl2shacl/blob/main/owl2sh-semi-closed.ttl#L836

as such, allValuesFrom restrictions aren't correctly transformed.. 

Solution:

Use the same approach as used for [rdfsRange2shClassOrDatatype](https://github.com/sparna-git/owl2shacl/blob/main/owl2sh-closed.ttl#L279) also for `owlAllValuesFrom2shClassOrDatatype`.

**Comment by tfrancart** [comment]
Thanks for spotting and reporting this ! as a workaround, you could try looking in previous versions of the files to see if this function was present in earlier versions

**Comment by simonstey** [comment]
yeah as mentioned, I replaced the function with

```turtle
owl2sh-semi-closed:owlAllValuesFrom2shClassOrDatatype
  rdf:type sh:SPARQLRule ;
  rdfs:comment "For each owl:allValuesFrom restriction, create a corresponding sh:class or sh:datatype constraint." ;
  rdfs:label "owl:allValuesFrom with IRI to sh:class or sh:datatype" ;
  sh:construct """
      CONSTRUCT {
        ?propertyShape ?parameter ?allValuesFrom .
        # ?restriction owl2sh-semi-closed:mappedTo ?propertyShape .
      }
      WHERE {
        {
          $this rdfs:subClassOf ?restriction .
          ?restriction a owl:Restriction .
          FILTER isBlank(?restriction) .
        }
        ?restriction owl:onProperty ?property .
        ?restriction owl:allValuesFrom ?allValuesFrom .
        FILTER isIRI(?allValuesFrom) .
        BIND (owl2sh-semi-closed:getPropertyShape(?property, $this) AS ?propertyShape) .
        BIND (
          IF(
            (?allValuesFrom IN (xsd:boolean, xsd:string, xsd:date, xsd:double, xsd:dateTime, xsd:integer, xsd:float, xsd:duration, xsd:anyURI)),
            sh:datatype,
            sh:class
          )
          AS ?parameter
        ) .
      }
""" ;
  sh:order 4 ;
  sh:prefixes <http://data.sparna.fr/ontologies/owl2sh-semi-closed> ;
.
```

(and also added `xsd:double` to the list of datatypes for all relevant rules)

**Comment by tfrancart** [comment]
Fixed in 3 variants, added xsd:double and xsd:anyURI where it was missing. Thanks
